#!/bin/sh
svn status|while read type file
do
        case "$type" in
            "!")
            svn delete "$file"
            ;;
            "?")
            svn add "$file"
            ;;
        esac
done
svn ci -m "$1"
